CREATE TABLESPACE TS_CERGY_DATA DATAFILE 'cergy_data.dbf' SIZE 50M AUTOEXTEND ON;
CREATE TABLESPACE TS_PAU_DATA DATAFILE 'pau_data.dbf' SIZE 50M AUTOEXTEND ON;
CREATE TABLESPACE TS_INDEX DATAFILE 'index_data.dbf' SIZE 30M AUTOEXTEND ON;
CREATE TABLESPACE TS_HISTO DATAFILE 'histo_data.dbf' SIZE 30M AUTOEXTEND ON;

CREATE CLUSTER SITE_MATERIEL_LOCALISATION (id_site NUMBER)
TABLESPACE TS_CERGY_DATA;

CREATE INDEX idx_cluster_site ON CLUSTER SITE_MATERIEL_LOCALISATION;


CREATE TABLE SITE (
    id_site NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    code_site VARCHAR2(10) NOT NULL UNIQUE,
    nom VARCHAR2(100) NOT NULL,
    ville VARCHAR2(80) NOT NULL,
    actif CHAR(1) DEFAULT '1' CHECK (actif IN ('0', '1'))
) TABLESPACE TS_CERGY_DATA; 
CREATE TABLE LOCALISATION (
    id_localisation NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    batiment VARCHAR2(100),
    salle VARCHAR2(50),
    id_site NUMBER NOT NULL REFERENCES SITE(id_site)
) CLUSTER SITE_MATERIEL_LOCALISATION(id_site); 

CREATE TABLE ROLE (
    id_role NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    code_role VARCHAR2(20) NOT NULL UNIQUE,
    libelle VARCHAR2(100) NOT NULL
) TABLESPACE TS_CERGY_DATA; 

CREATE TABLE UTILISATEUR (
    id_user NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    login VARCHAR2(80) NOT NULL UNIQUE,
    nom VARCHAR2(80) NOT NULL,
    prenom VARCHAR2(80),
    email VARCHAR2(150) UNIQUE,
    statut VARCHAR2(20) DEFAULT 'ACTIF',
    id_site NUMBER NOT NULL REFERENCES SITE(id_site)
) TABLESPACE TS_CERGY_DATA; 

CREATE TABLE USER_ROLE_SITE (
    id_user NUMBER REFERENCES UTILISATEUR(id_user),
    id_role NUMBER REFERENCES ROLE(id_role),
    id_site NUMBER REFERENCES SITE(id_site),
    date_debut DATE DEFAULT SYSDATE,
    PRIMARY KEY (id_user, id_role, id_site)
) TABLESPACE TS_INDEX; 


CREATE TABLE MATERIEL (
    id_materiel NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    inventaire VARCHAR2(50) NOT NULL UNIQUE,
    nom VARCHAR2(100) NOT NULL,
    type_materiel VARCHAR2(40) NOT NULL,
    statut VARCHAR2(30) DEFAULT 'EN_SERVICE',
    id_site NUMBER NOT NULL REFERENCES SITE(id_site),
    id_localisation NUMBER REFERENCES LOCALISATION(id_localisation),
    id_user_responsable NUMBER REFERENCES UTILISATEUR(id_user),
    date_creation DATE DEFAULT SYSDATE,
    date_modification DATE
) CLUSTER SITE_MATERIEL_LOCALISATION(id_site);

CREATE TABLE HISTO_AFFECTATION (
    id_histo NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    id_materiel NUMBER NOT NULL REFERENCES MATERIEL(id_materiel),
    id_user NUMBER REFERENCES UTILISATEUR(id_user),
    id_site NUMBER NOT NULL REFERENCES SITE(id_site),
    date_debut DATE NOT NULL,
    date_fin DATE
) TABLESPACE TS_HISTO; 

CREATE TABLE EQUIPEMENT_RESEAU (
    id_equipement NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    nom VARCHAR2(100) NOT NULL,
    type VARCHAR2(50),
    ip_mgmt VARCHAR2(45),
    id_site NUMBER NOT NULL REFERENCES SITE(id_site)
) TABLESPACE TS_CERGY_DATA; 

CREATE TABLE INTERFACE_RESEAU (
    id_interface NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    nom VARCHAR2(80) NOT NULL,
    mac VARCHAR2(17) UNIQUE,
    debit_mbps NUMBER,
    mtu NUMBER DEFAULT 1500,
    id_materiel NUMBER REFERENCES MATERIEL(id_materiel),
    id_equipement NUMBER REFERENCES EQUIPEMENT_RESEAU(id_equipement),
    CONSTRAINT ck_iface_owner CHECK (
        (id_materiel IS NOT NULL AND id_equipement IS NULL)
        OR (id_materiel IS NULL AND id_equipement IS NOT NULL)
    )
) TABLESPACE TS_CERGY_DATA; 

CREATE TABLE VLAN (
    id_vlan NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    numero_vlan NUMBER NOT NULL,
    nom VARCHAR2(100),
    id_site NUMBER NOT NULL REFERENCES SITE(id_site)
) TABLESPACE TS_INDEX;

CREATE TABLE SOUS_RESEAU (
    id_sous_reseau NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    cidr VARCHAR2(45) NOT NULL UNIQUE,
    passerelle VARCHAR2(45),
    id_vlan NUMBER REFERENCES VLAN(id_vlan),
    id_site NUMBER NOT NULL REFERENCES SITE(id_site)
) TABLESPACE TS_CERGY_DATA; 

CREATE TABLE ADRESSE_IP (
    id_ip NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    adresse VARCHAR2(45) NOT NULL UNIQUE,
    version_ip NUMBER CHECK (version_ip IN (4,6)),
    id_sous_reseau NUMBER NOT NULL REFERENCES SOUS_RESEAU(id_sous_reseau),
    id_interface NUMBER REFERENCES INTERFACE_RESEAU(id_interface)
) TABLESPACE TS_CERGY_DATA; 

